### ISSUE TITLE
Default max-height is fixed 1080, instead of requesting frame-s original size

### ISSUE THREAD

**Issue by l00tzOMG** [Infiziert90/getnative#13]
It would be more consistent to get frame props and use its height as max_height instead of fixed 1080p. Especially for 4K material.

Cheers,

**Comment by Infiziert90** [comment]
Hi,

This is because getnative was never intended to go higher... We can't even say if it will work correctly with 4k material.

You can ask here (https://discord.gg/V5vaWwr) in the Channel #encode-autism for more information :)
