### ISSUE TITLE
Broken on VS R60

### ISSUE THREAD

**Issue by wiwaz** [Infiziert90/getnative#23]
`get_plugins()` is deprecated and has been removed with R60, getnative is no longer functional due to this.

**Comment by Infiziert90** [comment]
https://github.com/Infiziert90/getnative/commit/86e846787b75a22d77cca1ad0accd6af9f6940dc

All versions 3.1.0+ have been fixed, pls update your getnative

**Comment by Infiziert90** [comment]
Can you try 3.2.1 and see if the error is still showing up?
