### ISSUE TITLE
Script ends prematurely for lanczos5 when using BluBb-mADe's fork of vapoursynth-descale

### ISSUE THREAD

**Issue by bodayw** [Infiziert90/getnative#3]
Hi there,

While the script runs much faster with BluBb-mADe's fork of vapoursynth-descale, it always ends prematurely without any output when running lanczos with taps=5. All other modes seem to work just fine.

The original version of vapoursynth-descale always work for everything, apart from being very slow.

I am using Python 3.7 with VapourSynth R46 on Windows.

PS. I'm actually guessing this would be an issue on the BluBb-mADe's fork of vapoursynth-descale side, but that repo is not accepting issues, so I'm posting here hoping someone could look into this.

Thanks!

**Comment by BluBb-mADe** [comment]
Yea, It probably is a problem in my fork. I could look into it but the code really kind of bad and the original author is already working on a plain C rewrite for a lot more performance while including the performance tweaks natively. I'll decide if it is worth putting the time in as soon as [Frechdachs](https://github.com/Frechdachs) gives me an estimate on how long his rework might take.

**Comment by bodayw** [comment]
Thanks! Great to hear that a rework is already planned.

**Comment by BluBb-mADe** [comment]
Frechdachs seems to already have a working version and is currently just experimenting with simd optimization so it shouldn't take long before the new version is available. It would be a colossal waste of time to clean up the old version now.

**Comment by Infiziert90** [comment]
@bodayw With the 2.0 release this is "fixed" ... descale_getnative will not run lanczos5, but you can have the original descale installed and getnative will use that for lanczos5.
Having both installed is possible with the fork https://github.com/OrangeChannel/vapoursynth-descale because it uses the descale_getnative namespace.
