### ISSUE TITLE
Please use one .py file

### ISSUE THREAD

**Issue by YomikoR** [Infiziert90/getnative#8]
Or at least rename the file `utils.py`. This is because getnative could be a portable script placed in `PATH` if you call `getnative.py ...` instead of `python getnative.py ...` or even `python path/to/getnative.py ...`, while something named "utils.py" shouldn't be there.

**Comment by Infiziert90** [comment]
@YomikoR 
The new release should be the best solution for the future:
https://github.com/Infiziert90/getnative/releases/tag/2.1.0

**Comment by YomikoR** [comment]
It makes my proposal so dumb. Thank you!
